/**
 * Seed D1 from catalog.seed.json.
 * Usage: wrangler d1 execute kinneykarate-db --local --file=db/seed.sql
 * Or generate SQL:  node db/seed.js > db/seed.sql
 */
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dir = dirname(fileURLToPath(import.meta.url));
const catalog = JSON.parse(readFileSync(join(__dir, 'catalog.seed.json'), 'utf8'));

const lines = [];
const q = (s) => `'${String(s ?? '').replace(/'/g, "''")}'`;
const qi = (n) => n == null ? 'NULL' : String(Math.round(Number(n)));

let productId = 1;
let variantId = 1;
let componentId = 1;

for (const [sortOrder, p] of catalog.products.entries()) {
  const kind = p.kind ?? 'simple';
  const fulfillment = p.fulfillment_type ?? 'made_to_order';
  const special = p.special_order ? 1 : 0;

  lines.push(
    `INSERT INTO products (id, slug, name, description, category, kind, fulfillment_type, special_order, active, sort_order, image) VALUES ` +
    `(${productId}, ${q(p.slug)}, ${q(p.name)}, ${q(p.note ?? p.description ?? '')}, ${q(p.category ?? '')}, ${q(kind)}, ${q(fulfillment)}, ${special}, 1, ${sortOrder}, ${q(p.image ?? '')});`
  );

  if (kind === 'simple' && Array.isArray(p.variants)) {
    for (const v of p.variants) {
      const price = v.price_cents ?? null;
      const color = v.color ?? p.color ?? null;
      lines.push(
        `INSERT INTO variants (id, product_id, size, color, price_cents, active) VALUES ` +
        `(${variantId}, ${productId}, ${q(v.size)}, ${q(color)}, ${qi(price)}, 1);`
      );
      // stocked items get an inventory row
      if (fulfillment === 'stocked') {
        lines.push(`INSERT INTO inventory (variant_id, on_hand) VALUES (${variantId}, 0);`);
      }
      variantId++;
    }
  }

  if (kind === 'bundle') {
    // Bundle price variant — the "set" price row
    if (p.price_cents != null) {
      lines.push(
        `INSERT INTO variants (id, product_id, sku, price_cents, active) VALUES ` +
        `(${variantId}, ${productId}, 'set', ${qi(p.price_cents)}, 1);`
      );
      variantId++;
    }

    // Bundle components
    if (Array.isArray(p.components)) {
      for (const [ci, c] of p.components.entries()) {
        lines.push(
          `INSERT INTO bundle_components (id, bundle_product_id, component_name, size_options, required, sort_order) VALUES ` +
          `(${componentId}, ${productId}, ${q(c.name)}, ${q(JSON.stringify(c.size_options ?? c.sizes ?? []))}, ${c.required !== false ? 1 : 0}, ${ci});`
        );
        componentId++;
      }
    }
  }

  productId++;
}

console.log('-- Auto-generated by db/seed.js — do not edit manually');
for (const line of lines) console.log(line);
